Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Volo.Task.Database.Entities;
using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel;
using Volo.Task.Manucharyan_Ruben.Managers.MessageManager;

namespace Volo.Task.Manucharyan_Ruben.Areas.Admin.Controllers
{
    public class ClientController : BaseController
    {
        [HttpGet]
        public ActionResult AddClient()
        {
            return View(new ClientModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddClient(ClientModel clientModel)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<Client> client = (await _databaseManager.GetClients()).Where(c => c.Passport == clientModel.Passport
                                                                            || c.Email == clientModel.Email || c.Phone == clientModel.Phone);

                if (client.Count() != 0)
                {
                    ModelState.AddModelError("", $"{client.Last().FirstName} {client.Last().LastName} {Messages.ClientIsAlreadyExist}");
                    TempData["useAsPartial"] = true;
                    ViewBag.UseAsPartial = (bool?)TempData["useAsPartial"] ?? false;
                    return View(clientModel);
                }

                Client newClient = new Client
                {
                    FirstName = clientModel.FirstName,
                    LastName = clientModel.LastName,
                    Birthday = clientModel.Birthday,
                    Passport = clientModel.Passport,
                    Email = clientModel.Email,
                    Phone = clientModel.Phone
                };

                await _databaseManager.AddClient(newClient);
                TempData["useAsPartialWithMessage"] = true;
                return RedirectToAction("AllClients");
            }
            return View(clientModel);
        }

        [HttpGet]
        public async Task<ActionResult> AllClients(int page = 1)
        {
            IEnumerable<Client> clients = (await _databaseManager.GetClients()).Skip((page - 1) * 10).Take(10);
            IEnumerable<ClientModel> clientsModel = ClientModel.GetAllClients(clients);

            ViewBag.PageCount = (clients.Count() / 10) + 1;

            bool useAsPartialWithMessage = (bool?)TempData["useAsPartialWithMessage"] ?? false;

            if (useAsPartialWithMessage)
            {
                ViewBag.UseAsPartial = useAsPartialWithMessage;
                ViewBag.Message = Messages.ClientAddedSuccessfully;
            }
            return View(clientsModel);
        }

        [HttpGet]
        public async Task<ActionResult> EditClient(int id)
        {
            Client client = await _databaseManager.GetClient(id);
            ClientModel clientModel = ClientModel.GetClientModel(client);
            return View(clientModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditClient(ClientModel clientModel)
        {
            if (ModelState.IsValid)
            {
                Client client = new Client
                {
                    FirstName = clientModel.FirstName,
                    LastName = clientModel.LastName,
                    Birthday = clientModel.Birthday,
                    Passport = clientModel.Passport,
                    Email = clientModel.Email,
                    Phone = clientModel.Phone,
                    Id = clientModel.Id
                };

                await _databaseManager.ChangeClient(client);

                TempData["givAMessage"] = true;
                return RedirectToAction("ClientPage", new { id = client.Id });
            }
            return View(clientModel);
        }

        [HttpGet]
        public async Task<ActionResult> ClientPage(int id)
        {
            Client client = await _databaseManager.GetClient(id);
            ClientModel clientModel = ClientModel.GetClientModel(client);

            bool sentAMessage = (bool?)TempData["givAMessage"] ?? false;

            if (sentAMessage)
            {
                ViewBag.Message = Messages.ClientSuccessfullyEdited;
            }

            return View(clientModel);
        }

        [HttpGet]
        public async Task<ActionResult> DeleteClient(int id)
        {
            await _databaseManager.DeleteClient(id);
            return RedirectToAction("AllClients");
        }
    }
}

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Controllers/DepositController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Volo.Task.Database.DepositTypes;
using Volo.Task.Database.Entities;
using Volo.Task.Manucharyan_Ruben.Managers.DepositManager;
using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel;
using Volo.Task.Manucharyan_Ruben.Managers.MessageManager;

namespace Volo.Task.Manucharyan_Ruben.Areas.Admin.Controllers
{
    public class DepositController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult> AddDeposit(int id)
        {
            return View(await CreateDepositModelForView(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddDeposit(DepositModel depositModel)
        {
            ModelState["DepositType"].Errors.Clear();
            if (ModelState.IsValid)
            {
                depositModel.BankId = (await _databaseManager.GetBanks()).Where(b => b.Name == Request.Form["BankName"]).Last().Id;

                var deposits = (await _databaseManager.GetDeposits()).Where(d => d.ClientId == depositModel.ClientId && d.BankId == depositModel.BankId);
                if (deposits.Count() != 0)
                {
                    ModelState.AddModelError("", Messages.ClientAlreadyHaveADepositInThisBank);
                    return View(await CreateDepositModelForView(depositModel.ClientId));
                }

                depositModel.DepositType = AllDeposits.GetAll.Where(d => d.Name == Request.Form["DepositType"]).Last();

                depositModel.Deadline = depositModel.Deadline.AddHours(DateTime.Now.Hour).AddMinutes(DateTime.Now.Minute).AddSeconds(DateTime.Now.Second + 1);

                IDepositManager depositManager = new DepositManager();

                if (depositManager.CanAddDeposit(DateTime.Now, depositModel.Deadline, depositModel.DepositType, depositModel.Amount))
                {
                    decimal profit = depositManager.Profit(DateTime.Now, depositModel.Deadline, depositModel.DepositType, depositModel.Amount);

                    await depositManager.AddDeposit(depositModel.ClientId, depositModel.BankId, depositModel.DepositType.Id, depositModel.Amount, depositModel.Deadline, profit);

                    TempData["useAsPartialWithMessage"] = true;
                    return RedirectToAction("All");
                }
                else
                {
                    ViewBag.SomethingWrong = true;

                    ViewBag.depositType = depositModel.DepositType;

                    return View(await CreateDepositModelForView(depositModel.ClientId));
                }
            }
            else
            {
                return View(await CreateDepositModelForView(depositModel.ClientId));
            }
        }

        [HttpGet]
        public ActionResult DepositInfo(string depositName)
        {
            return Json(AllDeposits.GetAll.Where(d => d.Name == depositName || depositName == "Select deposit type"), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> All(int? id, int page = 1)
        {
            IEnumerable<Deposit> deposits =( await _databaseManager.GetDeposits()).Skip((page - 1) * 10).Take(10); 
            IEnumerable<Bank> banks = await _databaseManager.GetBanks();
            IEnumerable<Client> clients = await _databaseManager.GetClients();

            IEnumerable<DepositModel> depositsModel = DepositModel.GetAllDeposits(deposits.Where(d => id == null || d.BankId == id), clients, banks);
                                                                                                 

            ViewBag.PageCount = (deposits.Count() / 10) + 1;

            bool useAsPartialWithMessage = (bool?)TempData["useAsPartialWithMessage"] ?? false;

            if (useAsPartialWithMessage)
            {
                ViewBag.Message = Messages.DepositAddedSuccessfully;
            }


            return View("AllDeposits", depositsModel);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int depositId)
        {
            Deposit deposit = await _databaseManager.GetDeposit(depositId);
            deposit.Status = DepositStatus.Deleted.ToString();
            await _databaseManager.DeleteDeposit(depositId);

            return RedirectToAction("All");
        }

        [HttpGet]
        private async Task<DepositModel> CreateDepositModelForView(int clientId)
        {
            Client client = await _databaseManager.GetClient(clientId);

            List<Bank> banks = await _databaseManager.GetBanks();

            return new DepositModel
            {
                Banks = banks,
                Client = client
            };
        }

    }
}

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Client/AddClient.cshtml
@model Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel.ClientModel


@{

    var ajaxOptions = new AjaxOptions
    {
        UpdateTargetId = "content",
        LoadingElementId = "loadingElement"
    };

    if (ViewBag.UseAsPartial != null && ViewBag.UseAsPartial)
    {
        Layout = null;
    }

}

<div class="div_add">
    @using (Ajax.BeginForm("AddClient", "Client", ajaxOptions))
    {
        @Html.AntiForgeryToken()
        @Html.Label("First name")<br />
        @Html.ValidationMessageFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "textBox", placeholder = "First name" })<br />

        @Html.Label("Last name")<br />
        @Html.ValidationMessageFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "textBox", placeholder = "Last name" })<br />

        @Html.Label("Birthday")<br />
        @Html.ValidationMessageFor(m => m.Birthday)
        @Html.TextBoxFor(m => m.Birthday, new { @class = "textBox", type = "date" })<br />

        @Html.Label("Passport")<br />
        @Html.ValidationMessageFor(m => m.Passport)
        @Html.TextBoxFor(m => m.Passport, new { @class = "textBox", placeholder = "Passport" })<br />

        @Html.Label("Email")<br />
        @Html.ValidationMessageFor(m => m.Email)<br />
        @Html.TextBoxFor(m => m.Email, new { @class = "textBox", placeholder = "Email" })<br />

        @Html.Label("Phone")<br />
        @Html.ValidationMessageFor(m => m.Phone)
        @Html.TextBoxFor(m => m.Phone, new { @class = "textBox", placeholder = "Phone" })<br />
        <br />
        <br />

        @Html.ValidationSummary()

        <button class="btn_add btn btn-xs" type="submit" value="Add Bank"><img class="middleIco" src="~/Content/Icons/save-ico.png" /> Add Client</button>
        <img id="loadingElement" src="~/Content/Icons/loading-gif.gif" style="height:30px;width:30px;display:none " />

    }

</div>





@section ajaxScript
{
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
}

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Client/AllClients.cshtml
@using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel
@model IEnumerable<ClientModel>

@{
    if (ViewBag.UseAsPartial != null && ViewBag.UseAsPartial)
    {
        Layout = null;
        <script> MySuccessMessage("@ViewBag.Message")</script>
    }

}

<table class="table table-striped table-condensed table-responsive table-hover">
    <thead>
        <tr>
            <td>Firts Name</td>
            <td>Last Name</td>
            <td>Birthday</td>
            <td>Email</td>
            <td>Passport</td>
            <td>Phone</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.ActionLink(@item.FirstName, "ClientPage", new { @item.Id }) </td>
                <td>@Html.ActionLink(@item.LastName, "ClientPage", new { @item.Id })</td>
                <td>@item.Birthday.ToShortDateString()</td>
                <td>@item.Email</td>
                <td>@item.Passport</td>
                <td>@item.Phone</td>
                <td>
                    @Html.ActionLink("Add deposit","AddDeposit","Deposit",new { item.Id },null)<img class="middleIco" src="~/Content/Icons/add-ico.png" />
                </td>
                <td>
                    <img class="middleIco" src="~/Content/Icons/edit-ico.png" onclick='location.href="@Url.Action("EditClient", new { item.Id })"'  onmouseover='style="cursor: pointer;"' />
                    <img class="middleIco" src="~/Content/Icons/delete-ico.png" onclick='return MyConfirm("Are you sure want to delete client @item.FirstName @item.LastName ?" ,"@Url.Action("DeleteClient","Client",new { item.Id})")' onmouseover='style="cursor: pointer;"' /> 
                </td>
                
            </tr>
        }
    </tbody>

</table>

<div class="btn-group ">
    @Html.AddPegination((int)@ViewBag.PageCount, m => Url.Action("AllClients", new { page = m }))
</div>

<button type="button" class="btn_add btn btn-xs" onclick='location.href="@Url.Action("AddClient")"'><img class="middleIco" src="~/Content/Icons/add-ico.png" /> Add</button>

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Client/ClientPage.cshtml
@using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel
@model ClientModel

@{
    if (ViewBag.Message != null)
    {
        <script> MySuccessMessage("@ViewBag.Message")</script>
    }
}


<h2>Client's page</h2>

@Html.DisplayForModel()

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Client/EditClient.cshtml
@using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel
@model ClientModel



<h2>Edit client</h2>

<div class="div_add">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.Label("First name")<br />
        @Html.ValidationMessageFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "textBox", placeholder = "First name" })<br />

        @Html.Label("Last name")<br />
        @Html.ValidationMessageFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "textBox", placeholder = "Last name" })<br />

        @Html.Label("Birthday")<br />
        @Html.ValidationMessageFor(m => m.Birthday)
        @Html.TextBoxFor(m => m.Birthday, new { @class = "textBox"})<br />

        @Html.Label("Passport")<br />
        @Html.ValidationMessageFor(m => m.Passport)
        @Html.TextBoxFor(m => m.Passport, new { @class = "textBox", placeholder = "Passport" })<br />

        @Html.Label("Email")<br />
        @Html.ValidationMessageFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "textBox", placeholder = "Email" })<br />

        @Html.Label("Phone")<br />
        @Html.ValidationMessageFor(m => m.Phone)
        @Html.TextBoxFor(m => m.Phone, new { @class = "textBox", placeholder = "Phone" })<br />
        <br />
        <br />
        @Html.ValidationSummary()

        <button type="button" class="btn_cancel btn btn-xs" onclick="history.back()"><img class="smallIco" src="~/Content/Icons/cancel-ico.png" /> Cancel</button>

        <button class="btn_add btn btn-xs" type="submit" value="Add Bank"><img class="middleIco" src="~/Content/Icons/save-ico.png" /> Save</button>

    
    }

</div>