Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Volo.Task.Database.DepositTypes;
using Volo.Task.Database.Entities;
using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel;
using Volo.Task.Manucharyan_Ruben.Managers.FileManager;
using Volo.Task.Manucharyan_Ruben.Managers.MessageManager;

namespace Volo.Task.Manucharyan_Ruben.Areas.Admin.Controllers
{

    public class BankController : BaseController
    {
        [HttpGet]
        public ActionResult AddBank()
        {
            return View(new BankModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddBank(BankModel bankModel, HttpPostedFileBase Ico)
        {
            if (ModelState.IsValid)

            {
                var banks = (await _databaseManager.GetBanks()).Where(b => b.Name == bankModel.Name);
                if (banks.Count() != 0)
                {
                    ModelState.AddModelError("", Messages.BankIsAlreadyExist);
                    return View(bankModel);
                }

                string icoExtension = string.Empty;
                if (Ico != null)
                {
                    IFileManager fileManager = new FileManager();
                    icoExtension = fileManager.SaveFile(Ico, Server.MapPath($"/Content/Images/Banks_Icons/{bankModel.Name.Trim(' ')}"));
                }

                Bank bank = new Bank()
                {
                    Name = bankModel.Name,
                    Description = bankModel.Description,
                    Ico = icoExtension != string.Empty ? $"/Content/Images/Banks_Icons/{bankModel.Name}{icoExtension}" : string.Empty
                };

                await _databaseManager.AddBank(bank);
                TempData["Message"] = Messages.BankAddedSuccessfully;
                return RedirectToAction("AllBanks");
            }

            else
            {
                return PartialView(bankModel);
            }
        }

        [HttpGet]
        public async Task<ActionResult> AllBanks(int page = 1)
        {
            IEnumerable<Bank> banks = (await _databaseManager.GetBanks()).Skip((page - 1) * 10).Take(10);
            IEnumerable<BankModel> banksModel = BankModel.AllBanks(banks);

            ViewBag.PageCount = (banks.Count() / 10) + 1;

            ViewBag.Message = TempData["deleted"];

            return View(banksModel);
        }

        [HttpGet]
        public async Task<ActionResult> EditBank(int id)
        {
            Bank bank = await _databaseManager.GetBank(id);
            BankModel bankModel = BankModel.GetBankModel(bank);
            return View(bankModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditBank(BankModel bankModel, HttpPostedFileBase Ico)
        {
            if (ModelState.IsValid)
            {
                IFileManager fileManager = new FileManager();

                var bank = await _databaseManager.GetBank(bankModel.Id);

                if (bank.Name != bankModel.Name)
                {
                    fileManager.RenameFile(bank.Name, bankModel.Name, Server.MapPath($"/Content/Images/Banks_Icons/{bank.Name.Trim(' ')}"));
                    bank.Name = bankModel.Name;
                }

                if (bank.Description != bankModel.Description)
                {
                    bank.Description = bankModel.Description;
                }


                string iconExtension = string.Empty;
                if (Ico != null)
                {
                    iconExtension = fileManager.SaveFile(Ico, Server.MapPath($"/Content/Images/Banks_Icons/{bank.Name.Trim(' ')}"));
                    bank.Ico = $"/Content/Images/Banks_Icons/{bank.Name}{iconExtension}";
                }

                await _databaseManager.ChangeBank(bank);

                TempData["givAMessage"] = true;
                return RedirectToAction("BankPage", new { id = bank.Id });
            }

            return View(bankModel);
        }

        [HttpGet]
        public async Task<ActionResult> BankPage(int id)
        {
            bool sentAMessage = (bool?)TempData["givAMessage"] ?? false;
            if (sentAMessage)
            {
                ViewBag.Message = Messages.BankSuccessfullyEdited;
            }

            Bank bank = await _databaseManager.GetBank(id);
            BankModel bankModel = BankModel.GetBankModel(bank);
            return View(bankModel);
        }

        [HttpGet]
        public async Task<ActionResult> DeleteBank(int id)
        {

            List<Deposit> deposits = await _databaseManager.GetDeposits();

            var dep = deposits.Where(d => d.BankId == id);

            if (dep.Count() > 0)
            {
                IEnumerable<Client> clients = await _databaseManager.GetClients();
                IEnumerable<Bank> banks = (await _databaseManager.GetBanks());
                TempData["BankId"] = id;
                var depositViewModel = DepositModel.GetAllDeposits(deposits.Where(d => d.BankId == id), clients, banks);

                return View("DeleteBank", depositViewModel.ToList());
            }

            await _databaseManager.DeleteBank(id);
            TempData["deleted"] = Messages.BankDeleted;
            return RedirectToAction("AllBanks");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteBank(List<DepositModel> depositModels)
        {
            var deposits = await _databaseManager.GetDeposits();
            var banks = await _databaseManager.GetBanks();
            int oldBankId = (int)TempData["BankId"];
            using (var dbTransaction = new VoloTaskDatabaseEntities().Database.BeginTransaction())
            {
                foreach (var item in depositModels)
                {
                    try
                    {
                        int newBankId = banks.Where(b => b.Name == item.Bank.Name).Last().Id;
                        var oldDeposit = deposits.Where(d => d.BankId == oldBankId && d.ClientId == item.Client.Id).Last();

                        oldDeposit.Status = DepositStatus.BankRetired.ToString();


                        Deposit newDeposit = new Deposit
                        {
                            BankId = newBankId,
                            ClientId = item.Client.Id,
                            DepositId = oldDeposit.DepositId,
                            Profit = oldDeposit.Profit,
                            Deadline = oldDeposit.Deadline,
                            StartDate = oldDeposit.StartDate,
                            Amount = oldDeposit.Amount,
                            Status = DepositStatus.Shifted.ToString(),
                        };

                        await _databaseManager.AddDeposit(newDeposit);
                        await _databaseManager.DeleteDeposit(oldDeposit.Id);
                    }
                    catch
                    {
                        dbTransaction.Rollback();
                        throw;
                    }
                }
                try
                {
                    await _databaseManager.DeleteBank(oldBankId);
                    dbTransaction.Commit();
                }
                catch
                {
                    dbTransaction.Rollback();
                    throw;
                }

                TempData["deleted"] = Messages.BankDeleted;
            }
            return RedirectToAction("AllBanks");
        }
    }
}

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Controllers/DepositController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Volo.Task.Database.DepositTypes;
using Volo.Task.Database.Entities;
using Volo.Task.Manucharyan_Ruben.Managers.DepositManager;
using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel;
using Volo.Task.Manucharyan_Ruben.Managers.MessageManager;

namespace Volo.Task.Manucharyan_Ruben.Areas.Admin.Controllers
{
    public class DepositController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult> AddDeposit(int id)
        {
            return View(await CreateDepositModelForView(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddDeposit(DepositModel depositModel)
        {
            ModelState["DepositType"].Errors.Clear();
            if (ModelState.IsValid)
            {
                depositModel.BankId = (await _databaseManager.GetBanks()).Where(b => b.Name == Request.Form["BankName"]).Last().Id;

                var deposits = (await _databaseManager.GetDeposits()).Where(d => d.ClientId == depositModel.ClientId && d.BankId == depositModel.BankId);
                if (deposits.Count() != 0)
                {
                    ModelState.AddModelError("", Messages.ClientAlreadyHaveADepositInThisBank);
                    return View(await CreateDepositModelForView(depositModel.ClientId));
                }

                depositModel.DepositType = AllDeposits.GetAll.Where(d => d.Name == Request.Form["DepositType"]).Last();

                depositModel.Deadline = depositModel.Deadline.AddHours(DateTime.Now.Hour).AddMinutes(DateTime.Now.Minute).AddSeconds(DateTime.Now.Second + 1);

                IDepositManager depositManager = new DepositManager();

                if (depositManager.CanAddDeposit(DateTime.Now, depositModel.Deadline, depositModel.DepositType, depositModel.Amount))
                {
                    decimal profit = depositManager.Profit(DateTime.Now, depositModel.Deadline, depositModel.DepositType, depositModel.Amount);

                    await depositManager.AddDeposit(depositModel.ClientId, depositModel.BankId, depositModel.DepositType.Id, depositModel.Amount, depositModel.Deadline, profit);

                    TempData["useAsPartialWithMessage"] = true;
                    return RedirectToAction("All");
                }
                else
                {
                    ViewBag.SomethingWrong = true;

                    ViewBag.depositType = depositModel.DepositType;

                    return View(await CreateDepositModelForView(depositModel.ClientId));
                }
            }
            else
            {
                return View(await CreateDepositModelForView(depositModel.ClientId));
            }
        }

        [HttpGet]
        public ActionResult DepositInfo(string depositName)
        {
            return Json(AllDeposits.GetAll.Where(d => d.Name == depositName || depositName == "Select deposit type"), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> All(int? id, int page = 1)
        {
            IEnumerable<Deposit> deposits =( await _databaseManager.GetDeposits()).Skip((page - 1) * 10).Take(10); 
            IEnumerable<Bank> banks = await _databaseManager.GetBanks();
            IEnumerable<Client> clients = await _databaseManager.GetClients();

            IEnumerable<DepositModel> depositsModel = DepositModel.GetAllDeposits(deposits.Where(d => id == null || d.BankId == id), clients, banks);
                                                                                                 

            ViewBag.PageCount = (deposits.Count() / 10) + 1;

            bool useAsPartialWithMessage = (bool?)TempData["useAsPartialWithMessage"] ?? false;

            if (useAsPartialWithMessage)
            {
                ViewBag.Message = Messages.DepositAddedSuccessfully;
            }


            return View("AllDeposits", depositsModel);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int depositId)
        {
            Deposit deposit = await _databaseManager.GetDeposit(depositId);
            deposit.Status = DepositStatus.Deleted.ToString();
            await _databaseManager.DeleteDeposit(depositId);

            return RedirectToAction("All");
        }

        [HttpGet]
        private async Task<DepositModel> CreateDepositModelForView(int clientId)
        {
            Client client = await _databaseManager.GetClient(clientId);

            List<Bank> banks = await _databaseManager.GetBanks();

            return new DepositModel
            {
                Banks = banks,
                Client = client
            };
        }

    }
}

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Bank/AddBank.cshtml
@model  Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel.BankModel




<div class="div_add" >
    @using (Html.BeginForm("AddBank","Bank",FormMethod.Post,new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.Label("Name")<br />
        @Html.ValidationMessageFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "textBox", placeholder = "Bank's name" })
        <br /><br />

        @Html.Label("Description")<br />
        @Html.ValidationMessageFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "textBox", placeholder = "Description", })
        <br /><br />
        @Html.ValidationSummary()
        @Html.Label("Icon")<br />

        <img id="output" width="75" height="75" src="~/Content/Images/Banks_Icons/DefaultBankIco.jpg" />

        @Html.TextBox("Ico", "", new { type = "file", onchange = "loadFile(event)", style = "visibility:hidden;" })

        <button type="button" class="btn_add btn btn-xs" onclick="resetIcon(); document.getElementById('Ico').click()"><img class="middleIco" src="~/Content/Icons/change-ico.png" /> Change icon</button>
        <button type="button" class="btn_cancel btn btn-xs" onclick='document.getElementById("output").src ="/Content/Images/Banks_Icons/DefaultBankIco.jpg"'><img class="middleIco" src="~/Content/Icons/delete-ico.png" /> Restore icon</button>
        <br />
        <br />

        <button class="btn_add btn btn-xs" type="submit"  value="Add Bank"><img class="middleIco" src="~/Content/Icons/save-ico.png" /> Add bank </button>
        <img id="loadingElement" src="~/Content/Icons/loading-gif.gif" style="height:30px;width:30px;display:none"; />

    }
</div>

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Bank/AllBanks.cshtml
@using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel
@model IEnumerable<BankModel>

@{

    if (ViewBag.Message != null)
    {
        <script> MySuccessMessage("@ViewBag.Message")</script>
    }
 

    ViewBag.Title = "Index";
}

<table class="table table-striped table-condensed table-responsive table-hover">
    <thead>
        <tr>
            <td></td>
            <td>Bank Name</td>
            <td>Bank Deskription</td>
            <td></td>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
            {
            <tr>

                <td><img src="@Url.Content($"~/{item.Ico}")" onerror="this.src='@Url.Content("~/Content/Images/Banks_Icons/DefaultBankIco.jpg")'" style="width:25px;height:25px;" alt="bank" /></td>

                <td>@Html.ActionLink(@item.Name, "BankPage", new { item.Id }) </td>
                <td>@item.Description</td>
                <td>@Html.ActionLink("Deposits","All","Deposit",new {id = item.Id },null)<img class="middleIco" src="~/Content/Icons/deposit-ico.png" /></td>
                <td>
                    <img class="middleIco" src="~/Content/Icons/edit-ico.png" onclick='location.href="@Url.Action("EditBank",new { item.Id })"' onmouseover='style="cursor: pointer;"' /> 
                    <img class="middleIco" src="~/Content/Icons/delete-ico.png" onclick='location.href="@Url.Action("DeleteBank","Bank",new { item.Id})"' onmouseover='style="cursor: pointer;"'/>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="btn-group ">
      @Html.AddPegination((int)@ViewBag.PageCount,m => Url.Action("AllBanks", new { page = m }))
</div>

<div style="float:right">
    <button type="button" class="btn_add btn btn-xs" onclick='location.href="@Url.Action("AddBank","Bank")"'><img class="middleIco" src="~/Content/Icons/add-ico.png" /> Add</button>
</div>

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Bank/BankPage.cshtml
@using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel
@model BankModel

@{
    if (ViewBag.Message != null)
    {
        <script> MySuccessMessage("@ViewBag.Message")</script>
    }
}




<h2>Bank page</h2>

<table>
    <thead>
        <tr>
            <td></td>
            <td>Bank's name</td>
            <td>Bank's description</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><img src="@Url.Content($"~/{Model.Ico}")" onerror="this.src='@Url.Content("~/Content/Images/Banks_Icons/DefaultBankIco.jpg")'" style="width:50px;height:50px;" /></td>
            <td>@Model.Name</td>
            <td>@Model.Description</td>
        </tr>
    </tbody>
</table>

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Bank/DeleteBank.cshtml
@model List<Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel.DepositModel>

@{
    if (ViewBag.Message != null)
    {
        <script> MySuccessMessage("@ViewBag.Message")</script>
    }
}


<p>@Model.Select(m=>m.Bank.Name).Last() 's deposits</p>

@using (Html.BeginForm())
{
  

<table>
    <thead>
        <tr>
            <th>Client's Name</th>
            <th>Deposit's Type</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count(); i++)

        {
            @Html.HiddenFor(m=>m[i].Client.Id )
            @Html.HiddenFor(m => m[i].DepositType.Id)
         
            <tr>
                <td>@Html.DisplayFor(m=>m[i].Client.FirstName)</td>
                <td>@Html.DisplayFor(m=>m[i].DepositType.Name)</td>
                <td>@Html.DropDownListFor(m=>m[i].Bank.Name, new SelectList(Model[i].Banks.Where(b=>b.Id != Model.Select(m=>m.Bank.Id).Last()).Select(b => b.Name)))</td>
            </tr>
        }
    </tbody>
</table>

<input type="submit" value="Save" />
}

Volo.Task.Manucharyan_Ruben/Volo.Task.Manucharyan_Ruben/Areas/Admin/Views/Bank/EditBank.cshtml
@using Volo.Task.Manucharyan_Ruben.Areas.Admin.ViewModel
@model BankModel

<h2>Edit bank</h2>

<div class="div_add">
    @using (Html.BeginForm("EditBank", "Bank", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.Label("Name")<br />
        @Html.ValidationMessageFor(m=>m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "textBox", placeholder = "Bank's name" })
        <br /><br />

        @Html.Label("Description")<br />
        @Html.ValidationMessageFor(m=>m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "textBox", placeholder = "Description" })
        <br /><br />
        @Html.ValidationSummary()

        @Html.Label("Icon")<br />

        <img id="output" src="@Url.Content($"~/{Model.Ico}")" onerror="this.src='@Url.Content("~/Content/Images/Banks_Icons/DefaultBankIco.jpg")'" style="width:75px;height:75px;" alt="bank" />

        @Html.TextBox("Ico", "", new { type = "file", onchange = "loadFile(event)", style = "visibility:hidden;" })
        

        <button type="button" class="btn_cancel btn btn-xs" onclick='resetIcon();document.getElementById("output").src ="@Url.Content($"~/{Model.Ico}")"'><img class="middleIco" src="~/Content/Icons/delete-ico.png" />Restore icon</button>


        <button type="button" class="btn_add btn btn-xs" onclick="document.getElementById('Ico').click()"><img class="middleIco" src="~/Content/Icons/change-ico.png" /> Change icon</button>

        <br />
        <br />

        <button type="button" class="btn_cancel btn btn-xs" onclick="history.back()"><img class="smallIco" src="~/Content/Icons/cancel-ico.png" /> Cancel</button>

        <button class="btn_add btn btn-xs" type="submit" value="Sace Changes"><img class="middleIco" src="~/Content/Icons/save-ico.png" /> Save Changes</button>

    }

</div>